# Generated by Django 2.2.7 on 2019-11-20 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='category',
        ),
    ]
