# Generated by Django 2.2.7 on 2019-11-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_note_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='color',
            new_name='category',
        ),
        migrations.AddField(
            model_name='note',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
